on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          php update.php
      - uses: test-room-7/action-update-file@v1.6.0
        with:
          file-path: docs/index.html
          commit-msg: Rebuild timeline
          github-token: ${{ secrets.GITHUB_TOKEN }}
